[tool.black]
line-length = 119
target-version = ['py38']

[tool.ruff]
lint.ignore = ["E501", "E741", "W605"]
lint.select = ["E", "F", "I", "W"]
line-length = 119

[tool.ruff.isort]
lines-after-imports = 2
known-first-party = ["src"]

[tool.jedi]
environment = "/home/toolkit/.conda/envs/trl_summarize" 
