task_type: "tldr"
output_dir: dpo_pythia410m_tldr
run_name: dpo_pythia410m_tldr
# hub_model_id: "mnoukhov/pythia410m-dpo-tldr-full"
push_to_hub: False
model_name_or_path: "mnoukhov/pythia410m-sft-tldr"
dataset_name: mnoukhov/summarize_from_feedback_oai_preprocessing_1706381144_relabel_pythia1b
dataset_test_split: validation
learning_rate: 1.0e-6
lr_scheduler_type: cosine
fp16: True
gradient_accumulation_steps: 4
per_device_train_batch_size: 4
per_device_eval_batch_size: 8
num_train_epochs: 1
max_length: 640
max_prompt_length: 512
max_target_length: 128
beta: 0.05
## peft
# loss_type: sigmoid
use_peft: False
gradient_checkpointing: False
## save strategy
evaluation_strategy: "steps"
eval_steps: 0.2
save_strategy: steps
save_steps: 0.2
hub_strategy: all_checkpoints
logging_steps: 100
ddp_find_unused_parameters: False
