wandb_run_id: snow
ref_model_name: mnoukhov/pythia410m-sft-tldr
gold_model_name: cleanrl/EleutherAI_pythia-6.9b-deduped__reward__tldr
gold_tokenizer_name: EleutherAI/pythia-6.9b-deduped
batch_size: 8
