# model_name_or_path: /home/toolkit/snapshots/fa0277d307db882ff9735fe0edc03cfb24a59442/dpo_pythia410m_tldr
wandb_run_id: snow
# wandb_log_id: eknajuax
# model_paths: [checkpoint-291]
save_generations: True
dataset_name: vwxyzjn/summarize_from_feedback_tldr_3_filtered_oai_preprocessing_1706381144
gold_model_name: cleanrl/EleutherAI_pythia-1b-deduped__reward__tldr
gold_tokenizer_name: EleutherAI/pythia-1b-deduped
max_new_tokens: 128
temperature: 0.010001
generate_batch_size: 16
eval_batch_size: 8
