task_type: tldr
wandb_run_id: snow
output_dir: onlinedpo_pythia410m_tldr
run_name: onlinedpo_pythia410m_tldr
dataset_name: vwxyzjn/summarize_from_feedback_tldr_3_filtered_oai_preprocessing_1706381144
dataset_test_split: validation
max_length: 512
fp16: True
## online dpo stuff
loss_type: sigmoid
## ppo stuff
total_episodes: 640000
response_length: 53
num_ppo_epochs: 1
num_mini_batches: 1 
learning_rate: 3.0e-6
per_device_train_batch_size: 8
gradient_accumulation_steps: 16
model_name_or_path: mnoukhov/pythia410m-sft-tldr 
sft_model_path: mnoukhov/pythia410m-sft-tldr 
reward_model_path: mnoukhov/pythia410m-rm-tldr 
local_rollout_forward_batch_size: 32
non_eos_penalty: True
stop_token: eos
# evaluation_strategy: "steps"
# eval_steps: 0.2
## save strategy
save_strategy: steps
save_steps: 0.2
hub_strategy: all_checkpoints
logging_steps: 100
num_sample_generations: 5
save_generations: True
